#!/bin/bash

INTERVAL=600
if [[ "$1" = "--interval" ]] && shift; then
  INTERVAL="$1" && shift
fi

kill_proc() {
  if kill -0 "$2" &>/dev/null; then
    disown "$2"
    # PGID=$(ps -o pgid= "$2" | tr -d ' ')
    # echo $PGID
    # echo $$
    # TODO: kill process group?
    kill -"$1" "$2" &>/dev/null || true
  fi
}

clean_up() {
  kill_proc 9 "$PID"
  while kill -0 "$PID" &>/dev/null; do
    sleep 1
  done
  exit "$(wait "$PID"; echo $?)"
}
trap clean_up SIGHUP SIGINT SIGQUIT SIGTERM

while true; do
  echo "$@"
  # TODO: setsid?
  sh -c "$*" &
  PID="$!"
  i=0
  while kill -0 "$PID" &>/dev/null && test "$i" -lt "$INTERVAL"; do
    sleep 1
    i=$((i + 1))
  done
  kill_proc 9 "$PID"
done
