#!/bin/bash
set -euxo pipefail

src=~/Dropbox
if [[ ! -d "$src" ]]; then
  src=~/Documents/Dropbox
  if [[ ! -d "$src" ]]; then
    exit 1
  fi
fi

shopt -s nullglob
for target in /media/*/Dropbox /media/"$USER"/*/Dropbox /Volumes/*/Dropbox; do
  echo "Start backup from $src to $target."
  rsync -av --delete "$src/" "$target/"
done
