#!/bin/bash
shopt -s nullglob
test -t 1 && exec \
  1> >(LC_ALL=C sed -u '/^\./s/^/'$'\e''[34m/; /^\*/s/^/'$'\e''[35m/;
               /^[><c]/s/^/'$'\e''[36m/; s/$/'$'\e''[0m/' >&1) \
  2> >(LC_ALL=C sed -u 's/^/'$'\e''[90m/; s/$/'$'\e''[0m/' >&2)
set -euxo pipefail

for src in ~/Dropbox ~/Documents; do
  for target in /Volumes/*/"${src##*/}" /media/"$USER"/*/"${src##*/}"; do
    if [[ $(realpath "${target%/*}") != "/" ]]; then
      echo "Start backup from $src to $target."
      rsync -av --delete --itemize-changes "$src/" "$target/"
    fi
  done
done
