#!/bin/bash

abort() {
  echo "${BASH_SOURCE[0]##*/}: $*" >&2
  exit 1
}

if (($# < 3)); then
  abort "specify low, high, script (% is replaced)"
fi

low=$1
high=$2
script=${*:3}

if [[ ! $low =~ ^[+-]?[0-9]+$ ]]; then
  abort "first argument should be an integer"
fi

if [[ ! $high =~ ^[+-]?[0-9]+$ ]]; then
  abort "second argument should be an integer"
fi

if ((low >= high)); then
  abort "first argument should be lower than second argument"
fi

while ((low < high)); do
  mid=$((low + (high - low) / 2))
  if bash -c "${script//%/$mid}"; then
    echo "$mid: good"
    low=$((mid + 1))
  else
    echo "$mid: bad"
    high=$mid
  fi
done

echo "$high is the bad number"
