#!/bin/bash
set -euo pipefail

before=$(mktemp)
after=$(mktemp)
trap 'rm -f "$before" "$after"' EXIT

{ defaults read; defaults -currentHost read; } >"$before"
read -p "Change configuration and press enter: " -r
{ defaults read; defaults -currentHost read; } >"$after"

vimdiff "$before" "$after"
