#!/usr/bin/env bash
set -euo pipefail

cmdname="$(basename "${BASH_SOURCE[0]}")"

before=$(mktemp -t "$cmdname.before")
after=$(mktemp -t "$cmdname.after")

clean_up() {
  rm -rf "$before" "$after"
}
trap clean_up EXIT

{ defaults read; defaults -currentHost read; } > "$before"
read -p "Change configuration and press enter: " -r
{ defaults read; defaults -currentHost read; } > "$after"

vimdiff "$before" "$after"
