#!/bin/bash
set -u

if [[ $# -eq 0 ]]; then
  exit 0
elif [[ $1 =~ ^(https://|git@)github(\.[[:alpha:]]+)+[/:][^/[:space:]]+/[^/[:space:]]+(/|\.git)?$ ]]; then
  git clone "$1"
elif command -v curl &>/dev/null; then
  curl -ORLk "$1"
elif command -v wget &>/dev/null; then
  wget --no-check-certificate --user-agent=download "$1"
fi
shift
$0 "$@"
