#!/bin/bash
set -eu

abort() {
  echo "${BASH_SOURCE[0]##*/}: $*" >&2
  exit 1
}

if [ $# -ge 2 ]; then
  abort "too many arguments"
fi

case "${1:-start}" in
  start|init)
    open -a Dropbox
    ;;
  stop|kill)
    pkill -x Dropbox
    ;;
  *)
    abort "unknown command: $1"
    ;;
esac
