#!/usr/bin/env bash
set -eu

cmdname="$(basename "${BASH_SOURCE[0]}")"

if [ $# -ge 2 ]; then
  echo "$cmdname: too many arguments" > /dev/stderr
  exit 1
fi

subcmd=${1:-start}

case "$subcmd" in
  start|init)
    open -a Dropbox
    ;;
  stop|kill)
    osascript -e 'tell application "Dropbox" to quit'
    ;;
  *)
    echo "$cmdname: unknown command: $subcmd" > /dev/stderr
    exit 1
    ;;
esac
