#!/bin/bash
set -euo pipefail

shopt -s nullglob
(($# == 0)) && set -- /media/* /media/"$USER"/* /Volumes/*
for dir in "$@"; do
  if [[ "$(readlink "$dir")" != "/" && "$dir" != "/media/$USER" && "$dir" != "/Volumes/Preboot" ]]; then
    echo "Ejecting $dir."
    if [[ "$OSTYPE" == darwin* ]]; then
      sudo diskutil umount "$dir"
    elif [[ -x /usr/bin/eject ]]; then
      sudo /usr/bin/eject "$dir"
    fi
  fi
done
