#!/usr/bin/env bash

while IFS= read -r -d '' file; do
  mtime=$(git log -1 --format=%ci "$file")
  t=$(echo "$mtime" | sed 's/[-+][0-9]*$//' | sed 's/[-: ]//g' | sed 's/\(..\)$/.\1/')
  echo "$(printf "%-80s" "$file")"$'\t'"$mtime"
  touch -at "$t" -mt "$t" "$file"
done < <(git ls-files -z)
