#!/bin/bash
set -euo pipefail

if [[ $# -ne 1 ]]; then
  echo "${BASH_SOURCE[0]##*/}: specify base branch" >&2
  exit 1
fi

if ! git diff-index --quiet --ignore-submodules HEAD; then
  git stash
  trap 'git stash pop' EXIT
fi

git rebase --onto "$1" "$(git merge-base "$1" HEAD)"
