#!/usr/bin/env bash
set -eu

if command -v gdate >/dev/null 2>&1; then
  datecmd="gdate"
else
  datecmd="date"
fi

while IFS= read -r -d '' file; do
  logtime=$(git log -1 --format=%ci "$file")
  mtime=$("$datecmd" -d "$logtime" +%Y%m%d%H%M.%S)
  if [ "$mtime" == "X" ]; then
    exit 1
  fi
  echo "$(printf "%-80s" "$file")"$'\t'"$logtime"$'\t'"$mtime"
  touch -t "$mtime" "$file"
done < <(git ls-files -z)
