#!/bin/bash
set -eu

branch-exists() {
  git rev-parse "origin/$1" &>/dev/null
}

rebase-onto() {
  git rebase --onto "origin/$1" "$(git log --merges --oneline -1 --format=%H)"
}

has_diff=$(git diff --ignore-submodules | grep -q '^' || echo 1)

if test -z "$has_diff"; then
  git stash
fi

git fetch

if branch-exists develop; then
  rebase-onto develop
elif branch-exists staging; then
  rebase-onto staging
elif branch-exists master; then
  rebase-onto master
else
  echo "Unknown main branch: cannot find develop, staging and master" >/dev/stderr
  exit 1
fi

if test -z "$has_diff"; then
  git stash pop
fi
