#!/usr/bin/env bash

while IFS= read -r -d '' file; do
  mtime=$(git log -1 --format=%cI "$file")
  t=$(gdate -d "$mtime" +%Y%m%d%H%M.%S)
  echo "$(printf "%-80s" "$file")"$'\t'"$mtime"$'\t'"$t"
  touch -at "$t" -mt "$t" "$file"
done < <(git ls-files -z)
