#!/usr/bin/env bash
set -eu

cmdname="$(basename "${BASH_SOURCE[0]}")"
dir=$(mktemp -d -t "$cmdname.XXXXXX")

clean_up() {
  chmod -R 700 "$dir"
  rm -rf "$dir"
}
trap clean_up EXIT

export GO111MODULE=on
export GOBIN=${GOPATH:-$(go env GOPATH)}/bin
export GOPATH=$dir

for f in "$@"; do
  go get -u "$f"
done
