#!/usr/bin/env bash
set -euo pipefail

GOTIP="$(go env GOPATH)/bin/gotip"
if [[ ! -x "$GOTIP" ]]; then
  go get golang.org/dl/gotip
fi

if [[ ! -d ~/.share/sdk ]]; then
  "$GOTIP" download
  mv ~/sdk ~/.share/sdk
fi

if [[ ! -e ~/sdk ]]; then
  ln -s ~/.share/sdk ~/sdk
  trap 'rm -f ~/sdk' EXIT
fi

"$GOTIP" "$@"
