#!/usr/bin/env bash
set -euo pipefail

NAME="${0##*/}"
GO="$(go env GOPATH)/bin/$NAME"
if [[ ! -x "$GO" ]]; then
  go install "golang.org/dl/$NAME@latest"
fi

if [[ ! -d ~/.share/sdk ]]; then
  "$GO" download
  mv ~/sdk ~/.share/sdk
fi

if [[ ! -e ~/sdk ]]; then
  ln -s ~/.share/sdk ~/sdk
  trap 'rm -f ~/sdk' EXIT
  if [[ ! -d ~/.share/sdk/"$NAME" ]]; then
    "$GO" download
  fi
elif [[ -L ~/sdk ]]; then
  trap 'rm -f ~/sdk' EXIT
fi

"$GO" "$@"
