#!/bin/sh
# Ref: http://blog.kamipo.net/entry/2013/02/20/122225
if command -v python > /dev/null 2>&1; then
  if python -V 2>&1 | grep -qm1 'Python 3\.'; then
    python -m http.server 8000
  else
    python -m SimpleHTTPServer 8000
  fi
elif command -v ruby > /dev/null 2>&1; then
  ruby -rwebrick -e 'WEBrick::HTTPServer.new(:Port => 8000, :DocumentRoot => ".").start'
elif command -v php > /dev/null 2>&1 && php -v | grep -qm1 'PHP 5\.[45]\.'; then
  php -S 0.0.0.0:8000
elif command -v plackup > /dev/null 2>&1; then
  plackup -MPlack::App::Directory -e 'Plack::App::Directory->new(root => ".")->to_app'
elif command -v erl > /dev/null 2>&1; then
  erl -eval 'inets:start(), inets:start(httpd, [{server_name, "httpd"}, {server_root, "."}, {document_root, "."}, {port, 8000}])'
fi
