#!/bin/bash
set -euo pipefail

abort() {
  echo "${BASH_SOURCE[0]##*/}: $*" >&2
  exit 1
}

if [[ "$#" -eq 0 ]]; then
  abort "service name required"
fi

if [[ -z "${MACKEREL_APIKEY:-}" ]]; then
  abort "specify \$MACKEREL_APIKEY"
fi

service="service=$1"
shift

roles=""
for role in "$@"; do
  roles="$roles&role=$role"
done

status="&status=working&status=standby"

cache=~/.cache/role/$service$(tr '&' '_' <<< "$roles").json
mkdir -p "${cache%/*}"

response=$(\
  curl -s \
    -H "X-Api-Key: $MACKEREL_APIKEY" \
    -X GET "https://api.mackerelio.com/api/v0/hosts?$service$roles$status"\
)
if [[ "$response" == *'"error":'* ]]; then
  echo "$response" >&2
  if [ -e "$cache" ]; then
    jq -M -r ".hosts[].name" < "$cache"
    exit 0
  fi
  exit 1
fi

tee "$cache" <<< "$response" | jq -M -r ".hosts[].name"
