#!/bin/bash
set -euo pipefail

abort() {
  echo "${BASH_SOURCE[0]##*/}: $*" >&2
  exit 1
}

if [[ "$#" -eq 0 ]]; then
  abort "service name is required"
fi

if [[ -z "${MACKEREL_APIKEY:-}" ]]; then
  abort "specify \$MACKEREL_APIKEY"
fi

service="service=$1"
roles="$(printf '&role=%s' "${@:2}")"
statuses="$(printf '&status=%s' working standby)"

cache=~/.cache/role/$service${roles//&/_}.json
mkdir -p "${cache%/*}"

if response="$(curl -sSf -H "X-Api-Key: $MACKEREL_APIKEY" \
  "https://api.mackerelio.com/api/v0/hosts?$service$roles$statuses")"; then
  tee "$cache" <<<"$response"
elif [[ -f "$cache" ]]; then
  cat "$cache"
fi | jq -M -r ".hosts[].name"
