#!/usr/bin/env bash
set -eux

if ( set +x; command -v brew ) >/dev/null 2>&1; then
  {
    set +x
    if command -v pyenv; then
      export PATH=${PATH//$(pyenv root)\/shims:/}
    fi
    set -x
  } >/dev/null 2>&1
  brew update
  if pgrep -f "$(brew --prefix)/bin/vim" >/dev/null; then
    if ! brew list --pinned | grep vim >/dev/null; then
      brew pin vim
    fi
  else
    if brew list --pinned | grep vim >/dev/null; then
      brew unpin vim
    fi
  fi
  brew upgrade --ignore-pinned
  brew cleanup -s
  brew doctor
fi

{ set +x; } 2>/dev/null
test "$(date +%w)" -ne 0 && exit 0
set -x

if ( set +x; command -v miv ) >/dev/null 2>&1; then
  miv update
fi

if ( set +x; command -v rustup ) >/dev/null 2>&1; then
  rustup update stable
fi

if ( set +x; command -v stack ) >/dev/null 2>&1; then
  stack update
  stack upgrade
  stack clean
fi

if ( set +x; command -v zinit ) >/dev/null 2>&1; then
  zinit update
fi
