#!/bin/bash
set -eux

if ( set +x; command -v brew ) &>/dev/null; then
  {
    set +x
    if command -v pyenv; then
      export PATH=${PATH//$(pyenv root)\/shims:/}
    fi
    set -x
  } &>/dev/null
  brew update
  if pgrep -q -f "$(brew --prefix)/bin/vim"; then
    if ! brew list --pinned | grep -q vim; then
      brew pin vim
    fi
  else
    if brew list --pinned | grep -q vim; then
      brew unpin vim
    fi
  fi
  brew upgrade
  brew cleanup -s
  brew doctor
fi

if ( set +x; command -v miv ) &>/dev/null; then
  miv update
fi

if ( set +x; command -v rustup ) &>/dev/null; then
  rustup update stable
fi

if ( set +x; command -v stack ) &>/dev/null; then
  if ( set +x; command -v ghcup ) &>/dev/null; then
    ghcup upgrade
  else
    stack update
    stack upgrade
    stack clean
  fi
fi

if ( set +x; command -v zinit ) &>/dev/null; then
  zinit update
fi
